import TravelSVG from "./travel.svg?react"
import ChecklistSVG from "./checklist.svg?react"
import MissionSVG from "./mission.svg?react"
import ChevrontUpSVG from "./chevrontUp.svg?react"
import ChevrontDownSVG from "./chevrontDown.svg?react"
import TicketSVG from "./ticket.svg?react"
import PackageSVG from "./package-car.svg?react"
import ShieldSVG from "./shild.svg?react"
import CloudSVG from "./cloud.svg?react"
import IgIcon from "./ig.svg?react"
import LinkedInIcon from "./linkedIn.svg?react"
import GithubIcon from "./github.svg?react"
import DiscordIcon from "./discord.svg?react"
import MediumIcon from "./medium.svg?react"
import DribleIcon from "./drible.svg?react"
import TiketPesawatIcon from "./tiketpesaat.svg?react"
import AdventureIcon from "./adventure.svg?react"

export { TravelSVG, ChecklistSVG, MissionSVG, ChevrontDownSVG, ChevrontUpSVG, TicketSVG, PackageSVG, ShieldSVG, CloudSVG, DiscordIcon, DribleIcon, GithubIcon, IgIcon, LinkedInIcon, MediumIcon, TiketPesawatIcon, AdventureIcon }